# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testerhack', '0002_auto_20160310_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsUser',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('percentage', models.IntegerField(default=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
        migrations.RenameField(
            model_name='analyticsone',
            old_name='hit',
            new_name='visit',
        ),
        migrations.RenameField(
            model_name='analyticstwo',
            old_name='hit',
            new_name='visit',
        ),
        migrations.AlterField(
            model_name='analyticsone',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='analyticstwo',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
